#!/usr/bin/env bash
# Build dist/mage2x.plugin.zsh: every source inlined into one file.
#
# The repository stays multi-file because that is easier to read and is what the
# Oh My Zsh plugin loads. The bundle exists for delivery paths that can only
# carry one object — an S3 asset uploaded by Terraform, for instance, where the
# deployed version is pinned by the apply rather than by whatever HEAD holds
# when an instance happens to boot.
#
#   scripts/bundle.sh          write dist/mage2x.plugin.zsh
#   scripts/bundle.sh --check  exit 1 if dist/ is out of date (CI gate)
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO/dist/mage2x.plugin.zsh"
VERSION="$(node -p "require('$REPO/package.json').version" 2>/dev/null || echo unknown)"

# Order is irrelevant at definition time — the catalogue calls adapters only at
# run time — but keeping it identical to the plugin's own source loop means the
# bundle and the checkout cannot diverge in behaviour.
SOURCES=(lib/core.zsh lib/rt-cli.zsh lib/rt-kube.zsh lib/catalog.zsh)

build() {
  cat <<HEADER
# mage2x ${VERSION} - single-file build, generated by scripts/bundle.sh
#
# DO NOT EDIT. Edit the sources and re-run scripts/bundle.sh; CI fails when this
# file does not match them.
#
# This build inlines lib/*.zsh so the plugin works where only one file can be
# delivered. Behaviour is identical to the multi-file checkout.

HEADER

  local f
  for f in "${SOURCES[@]}"; do
    printf '# ---- %s %s\n' "$f" "$(printf '%.0s-' {1..40})"
    # Drop the shebang-less leading comment block? No: the per-file header is
    # part of why the source is readable, and it costs nothing here.
    cat "$REPO/$f"
    printf '\n'
  done

  printf '# ---- mage2x.plugin.zsh %s\n' "$(printf '%.0s-' {1..27})"
  # Strip the source loop: everything it would load is already above. Keep the
  # rest byte-for-byte so the two builds cannot drift in any other respect.
  awk '
    /^local _f$/            { skip = 1 }
    skip && /^unset _f$/    { skip = 0; next }
    skip                    { next }
    { print }
  ' "$REPO/mage2x.plugin.zsh"
}

if [[ "${1:-}" == "--check" ]]; then
  if [[ ! -f "$OUT" ]]; then
    echo "::error::dist/mage2x.plugin.zsh is missing - run scripts/bundle.sh" >&2
    exit 1
  fi
  if ! diff -q <(build) "$OUT" >/dev/null; then
    echo "::error::dist/mage2x.plugin.zsh is out of date - run scripts/bundle.sh" >&2
    diff <(build) "$OUT" | head -20 >&2
    exit 1
  fi
  echo "dist/mage2x.plugin.zsh matches the sources"
  exit 0
fi

mkdir -p "$REPO/dist"
build > "$OUT"
chmod 0644 "$OUT"
printf 'wrote %s (%s lines, %s bytes)\n' \
  "dist/mage2x.plugin.zsh" "$(wc -l < "$OUT" | tr -d ' ')" "$(wc -c < "$OUT" | tr -d ' ')"
